finished organizations and sponsors
NSS-Evening-E22/gitsub-ghostzen_teamplanning pull request #43
Opened 2023-02-10 17:43 UTC by littleg-cyber

2023-02-10 17:47 UTC, Mestany2 approved these changes

2023-02-10 17:53 UTC, Mestany2 reviewed
The navbar is there but it is missing the Discussion button that Jimmy added

2023-02-10 17:54 UTC, Mestany2 requested changes
Can you add your code to the latest main HTML version. 
It  is missing the button that Jimmy added

2023-02-11 15:13 UTC, jmmyfam approved these changes

2023-02-11 15:25 UTC, Mestany2 approved these changes

2023-02-11 15:25 UTC, merged